src/error.rs
Issue was caused by a couple of configuration checks.
=> Unbreak building of rustic_core-0.1.1 on OpenBSD (#27)

src/commands/backup.rs
I think this option is better suited there as it depends on and describes behavior about having a parent...
=> move skip-identical-parent option to ParentOptions

crates/core/src/archiver.rs, crates/core/src/backend.rs, crates/core/src/backend/ignore.rs, crates/core/src/backend/stdin.rs, crates/core/src/commands/backup.rs, crates/core/src/lib.rs
Breaking change: This removes the `impl Iterator` from `LocalSource`. To still be able to iterate over its entries, the `ReadSource` trait (and its `entries()` method) is now public.
The neccessary change for rustic is in https://github.com/rustic-rs/rustic/pull/966
closes  https://github.com/rustic-rs/rustic/issues/689
This PR is based on #73 which should be merged first
=> backup: run size scanning parallel to backup; add no-scan option

crates/backend/Cargo.toml, crates/backend/src/choose.rs, crates/backend/src/lib.rs, crates/backend/src/opendal.rs, crates/backend/src/opendal/sftp.rs
Note that sftp in opendal is currently only supported on unix, see https://github.com/apache/incubator-opendal/issues/2963
=> backend: Add sftp backend

crates/core/src/blob/packer.rs, crates/core/src/error.rs, crates/core/src/index/indexer.rs
closes https://github.com/rustic-rs/rustic/issues/1018
=> fix: don't abort on negative elapsed time in packer/indexer

Cargo.toml, README.md, crates/backend/README.md, crates/backend/src/rest.rs, crates/core/README.md, crates/core/src/blob.rs
`ahash` bumped their MSRV, we also bump ours now so other PRs are unblocked from CI failing.
=> fix: updated msrv and fix clippy lints

crates/core/src/commands/prune.rs
The reference for repacking that is both used for `--max-unused` and `--max-repack` was incomplete. In fact the packs which are at this point are only candidates for repacking (but not yet decided) were not taken into account. Sometimes this can be quite a lot and therefore explains why in a max-repack=10% example less than 10% was repacked. And in the max-unused=5% example it took the 5% of a much smaller amount of used data and hence tried to repack too much as the limit of still tolerated unused data is too low.
This has now been fixed.
closes https://github.com/rustic-rs/rustic/issues/1062
=> fix(prune): Correct number of repacks

crates/core/src/commands/restore.rs
Restoring with large pack size used too much memory.
This PR limits the amount of data being fetched at once from the backend and hence the total amount of memory used by this.
closes https://github.com/rustic-rs/rustic/issues/1067
=> fix(memory): Limit memory usage for restore when having large pack files

crates/core/src/commands/config.rs, crates/core/src/commands/prune.rs, crates/core/src/commands/repair/index.rs, crates/core/src/commands/repair/snapshots.rs, crates/core/src/error.rs, crates/core/src/repofile/configfile.rs, crates/core/src/repository.rs
This PR allows to configure a repository to be append-only. Commands which would not work on an append-only backend will no longer try to perform these operations when this option is set.
=> feat: Add append-only repository mode

crates/core/Cargo.toml, crates/core/src/blob/packer.rs, crates/core/src/commands/prune.rs
This PR creates and collects some additional debug information for a prune plan.
closes #137
=> feat(prune): Add more debug info to stats

crates/core/Cargo.toml, crates/core/src/backend/local_destination.rs
Due to a memory alignment bug, crashes on macOS happened. This is fixed by this dependency update.
closes https://github.com/rustic-rs/rustic/issues/1075
=> fix: update dependency nix

crates/core/src/commands/check.rs, crates/core/src/commands/repair/index.rs, crates/core/src/repofile/indexfile.rs, crates/core/src/repository.rs
This allows to use a repository even in the case of an defect index without running an index repair. Instead the information is read from the pack files and stored in-memory but not written.
This allows to use read-only commands on repository with defect index.
=> feat: Add Repository::to_indexed_checked and ::to_index_ids_checked()

crates/core/src/repository.rs
When the password is provided via the environment variable like `RUSTIC_PASSWORD=hunter2`, it would be visible in the help text:
```
--password <PASSWORD>     Password of the repository [env: RUSTIC_PASSWORD=hunter2]
```
To avoid exposing any sensitive information this commit hides the password from the help text:
```
--password <PASSWORD>     Password of the repository [env: RUSTIC_PASSWORD]
```
=> feat: Hide plain text password from help text

crates/core/src/archiver/parent.rs
When having a symlink which is already present in a parent snapshot, rustic set `content = []` instead of using the parent content. While this does no harm (for symlinks the content is anyway not read), it may lead to changed trees even though no change was actually performed. This PR fixes that.
=> fix: Set correct content for symlink with parent snapshot

Cargo.toml, crates/backend/Cargo.toml, crates/backend/src/error.rs, crates/backend/src/rclone.rs, crates/core/Cargo.toml
rclone version checking required a version in form "major.minor.patch". Now it supports all semver-compatible versions.
closes https://github.com/rustic-rs/rustic/issues/1097
fixes #6
=> fix(rclone): Use semver for version checking

crates/core/Cargo.toml, crates/core/src/backend/ignore.rs, crates/core/src/commands/forget.rs, crates/core/src/error.rs, crates/core/src/repofile/snapshotfile.rs, crates/core/src/repository.rs, crates/core/src/repository/warm_up.rs
Adds the possibility to specify many options in config profile files as single strings which required arrays of strings - in the case of the array only containing 1 entry.
Breaking change:
Also removes the splitting of one string from `password-command` and `warmup-command`. Now the already-split command has to be given as array (or single string if there are no arguments to the command).
=> feat!: Allow specifying many options in config profile without array

crates/core/src/repofile/snapshotfile.rs
See https://github.com/rustic-rs/rustic/issues/1135
=> fix(paths): Handle paths starting with "." correctly

crates/core/Cargo.toml, crates/core/src/backend/node.rs, crates/core/src/blob/tree.rs, crates/core/src/lib.rs, crates/core/src/repository.rs, crates/core/tests/integration.rs, crates/core/tests/snapshots/integration__find-matching-existing-nix.snap, crates/core/tests/snapshots/integration__find-matching-existing-windows.snap, crates/core/tests/snapshots/integration__find-matching-nodes-not-found-nix.snap, crates/core/tests/snapshots/integration__find-matching-nodes-not-found-windows.snap, crates/core/tests/snapshots/integration__find-matching-wildcard-existing-nix.snap, crates/core/tests/snapshots/integration__find-matching-wildcard-existing-windows.snap, crates/core/tests/snapshots/integration__find-nodes-existing-nix.snap, crates/core/tests/snapshots/integration__find-nodes-existing-windows.snap, crates/core/tests/snapshots/integration__find-nodes-not-found-nix.snap, crates/core/tests/snapshots/integration__find-nodes-not-found-windows.snap, examples/find/Cargo.toml, examples/find/examples/find.rs
Adds `Repository` methods to find a given path in multiple trees.
`find_nodes_from_path`: Searches for an explicitly given path
`find_matching_nodes`: Searches using an arbitrary matching criterion
=> feat: add search methods to Repository

crates/core/src/backend/ignore.rs, crates/core/src/error.rs
see https://github.com/rustic-rs/rustic/issues/1122
=> fix(errors): Show filenames in error message coming from ignore source

crates/core/src/backend/ignore.rs, crates/core/src/backend/local_destination.rs, crates/core/src/error.rs
=> feat(backend): Add error sources

crates/core/src/commands/repair/snapshots.rs, crates/core/src/repofile/snapshotfile.rs
We now use a sorted set for storing paths and tags used in snapshots. This ensures that independent from how they are saved, identical sets are always grouped together.
closes https://github.com/rustic-rs/rustic/issues/1158
=> fix: Always sort StringList

crates/core/src/lib.rs, crates/core/tests/integration.rs
See #227 for more details.
I've added a test-case which constructs a minimal wrapper type around a Repository that implements `IndexedFull`, puts two instances into a collection (the primary motivator behind this), and hands them to a function that relies on the trait.
=> fix: Export types so the Repository type can be fully specified

crates/core/src/backend/ignore.rs
This should fix rustic-rs/rustic_core#232 
However I'm not so sure as the error message I encountered is slightly different from what reported by the issue creator.
In both cases I think this PR is worth looking into when you have time.
Even on a system that supports extended-attributes, we might encounter some part of the file-system that doesn't.
For instance a `mount` with the right option (streams_interface=windows for instace) will not support xattr.
AFAIK it also seems to be the case with a simple sshfs on a debian/ubuntu (as experienced in  #232).
I used a debug log to print the XAttr error in order to avoid erroring for every file of an extended attribute incompatible backup.
I am once again unsure on what tests to add. 
Please let me know if anything comes up to your mind.
=> fix: backup file even if failed listing extended attributes

crates/core/src/backend/ignore.rs, crates/core/src/backend/local_destination.rs, crates/core/src/backend/node.rs, crates/core/src/blob/tree.rs
handle non-value xattr correctly and also allow to read xattr with `null` value.
closes https://github.com/rustic-rs/rustic/issues/1190
closes https://github.com/rustic-rs/rustic/issues/1189
=> fix: Allow non-value/null xattr

crates/backend/CHANGELOG.md, crates/backend/Cargo.toml, crates/config/CHANGELOG.md, crates/config/Cargo.toml, crates/core/CHANGELOG.md, crates/core/Cargo.toml
* `rustic_backend`: 0.1.1 -> 0.2.0 (✓ API compatible changes)
* `rustic_core`: 0.2.0 -> 0.3.0 (✓ API compatible changes)
* `rustic_config`: 0.1.0 -> 0.2.0 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- *(backends)* Add throttle option to opendal backend ([#216](https://github.com/rustic-rs/rustic_core/pull/216))
- *(backend)* [**breaking**] remove s3 and sftp wrapper around opendal ([#200](https://github.com/rustic-rs/rustic_core/pull/200))
- [**breaking**] move clippy lints to cargo manifest and fix upcoming issues all over the workspace ([#176](https://github.com/rustic-rs/rustic_core/pull/176))
- *(opendal)* Add option connections ([#155](https://github.com/rustic-rs/rustic_core/pull/155))
- clippy lints …
=> chore: release

crates/core/src/backend/ignore.rs
Building rustic_core on OpenBSD fails with:
```
error[E0412]: cannot find type `ExtendedAttribute` in this scope
--> /tmp/pobj/rustic-0.8.0/rustic-0.8.0/modcargo-crates/rustic_core-0.3.0/src/backend/ignore.rs:476:62
|
476 | ...usticResult<Vec<ExtendedAttribute>> {
|                    ^^^^^^^^^^^^^^^^^ not found in this scope
|
help: consider importing this struct
|
1   + use crate::backend::node::ExtendedAttribute;
|
```
Unbreak by fixing a conditional check.
=> fix(build): unbreak building on OpenBSD

crates/core/src/error.rs, crates/core/src/repository.rs
* When process spawning failed, e.g. command did not exist, then previously the only output was "error: No such file or directory" without any context about what Rustic was trying to do. This is changed.
* Also when `wait_with_output()` failed, the detailed error was not reported.
* Renamed error kind `PasswordCommandParsingFailed` to `PasswordCommandExecutionFailed` because the error conditions had nothing to do with parsing. (Also updated `rustic`: https://github.com/rustic-rs/rustic/pull/1237)
=> fix!: improve password-command error reporting

crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/lib.rs, crates/core/src/repository.rs, crates/core/src/repository/command_input.rs, crates/core/tests/command_input.rs
Add the new type CommandInput. This type supports serde and clap (using `FromStr`) and is supposed to be used where users need to specify commands which are to be executed.
There are 3 ways to define commands (here TOML is used):
- as one string: `command = "echo test"`
- as command and args as string array: `command = {command = "echo", args = ["test1", "test2"] }`
- additionally specify error treatment:  `command = {command = "echo", args = ["test1", "test2"], on_failure = "ignore" }`
In the first example the full command and the args are split using `shell_words` which requires special escaping or quoting when spaces are contained. In the other examples every string is taken literally as given (but TOML escapes may apply when parsing TOML).
This PR only adds the new type, using it on …
=> feat: Add CommandInput

crates/core/src/repofile/snapshotfile.rs
Fixes a regression about de/serializing tags, introduced by #267
=> fix: de/serialize tags as DisplayFromStr

crates/backend/README.md, crates/config/README.md, crates/core/README.md
People should set their own version here if they want it locked to a specific one. This section in the docs would need us to update it every time before we release a new version (major/minor). We can just use a star here and let the user decide.
People will use the copy function of crates.io anyway, I think:
=> doc: remove readme versions in usage section for easier release due to release PR

crates/core/src/backend/cache.rs
The default cache directory is now only queried if no explicit cache path is given. This is necessary to prevent errors on platforms where the default cache directory does not exist, like Android.
=> fix: Don't query the default cache directory when a custom one is set

.github/workflows/ci-heavy.yml
Due to extensive use of the merge queue, we essentially run the heavy ci twice. once in the merge group and then again when being pushed from the merge group to main. This wastes runner resources and time. Instead we can just run on schedule every night and count on the merge group CI runs.
=> ci: don't run heavy ci on push to main

crates/core/src/commands/check.rs
Fixes a regression introduced by #262: Check without `--read-data` throws lots of error because we changed the access to the index.
=> fix: fix check without --read-data

crates/core/src/commands/check.rs
Fixes https://github.com/rustic-rs/rustic/issues/1229
=> fix(errors): better error message for hot/cold repo in check

crates/core/src/crypto/aespoly1305.rs, crates/core/src/error.rs
=> fix(errors): use correct error variant for data encryption

crates/core/src/blob/tree.rs
=> refactor(errors): improve message and add logging when sending tree from backend panics

crates/core/src/commands/check.rs, crates/core/src/commands/init.rs, crates/core/src/commands/key.rs, crates/core/src/commands/prune.rs, crates/core/src/commands/repair/index.rs, crates/core/src/commands/repair/snapshots.rs, crates/core/src/commands/restore.rs, crates/core/src/repository.rs, crates/core/tests/command_input.rs, crates/core/tests/integration.rs
I saw in #224 that `CheckOptions::run()` has been moved to type `CheckResultsCollector`. In other commands we actually have functions, not associated to any type, that take their options as parameters. I applied this here to check, prune, repair, key, and restore as well. Because I think it reduces coupling and increases testability.
The idea behind having these standalone functions is, that check, prune, repair, key, and restore are not run on their options (as a method of e.g. `CheckOptions`), but rather take parameters, where one is the e.g. `CheckOption` itself.
In principle: methods that implement commands don't operate on their own options and have side effects on other types - options are passed into functions as parameters.
Furthermore, a `check()` on `CheckOptions` sounds if it …
=> refactor(commands): decouple logic from option structs for check, prune, repair, key, and restore

crates/core/src/blob/tree.rs
Reverts rustic-rs/rustic_core#314
Related https://github.com/rustic-rs/rustic/issues/1313
=> Revert "refactor(errors): improve message and add logging when sending tree from backend panics"

release-plz.toml
We don't want to update dependencies automatically, as currently our dependencies tree is broken somewhere. We also run renovate on a weekly schedule to update the lockfile.
=> chore(release): Disable automatic dependency updates

Cargo.lock, crates/backend/Cargo.toml, crates/backend/src/opendal.rs
We now always use UnixPaths to generate the path used in opendal URLs.
closes https://github.com/rustic-rs/rustic/issues/1162
closes https://github.com/rustic-rs/rustic/issues/1302
closes https://github.com/rustic-rs/rustic/issues/1305
=> fix: opendal paths on windows

crates/core/src/error.rs
This was based on a misunderstanding, how `thiserror` forwards the Display implementation when using `#[error(transparent)]` in combination with `displaydoc::Display` which resulted in:
```console
Error in cache backend removing Pack, <hash>: [`std::io::Error`]
```
being shown to the user.
=> fix(errors): forwarding Display impl should work again

Cargo.lock, crates/backend/Cargo.toml, crates/backend/src/rest.rs
Hello,
Removed the unmaintained  `backoff` crate in the `rustic_backend` crate.
Replaced it with the relatively similar `backon` crate.
If `backon` as simpler API, it also lacks a few features that `backoff` had.
For instance: `no_max_delay` or `backoff::retry_notify`. 
To make up for it:
- I opened https://github.com/Xuanwo/backon/pull/160 on the `backon` github.
- I implemented an internal module `backon_extension` inside `backend::rest`.
Let me know what you think of the code!
Fixes https://github.com/rustic-rs/rustic_core/issues/351
=> refactor(backend): migrate from `backoff` to `backon`

.cargo/audit.toml, Cargo.lock, crates/core/Cargo.toml, crates/core/src/blob/tree.rs, crates/core/src/repofile/snapshotfile.rs, deny.toml
=> chore(deps): remove Derivative and replace with Default impl due to RUSTSEC-2024-0388

crates/backend/src/local.rs, crates/backend/src/opendal.rs, crates/core/src/archiver.rs, crates/core/src/archiver/parent.rs, crates/core/src/backend/cache.rs, crates/core/src/backend/ignore.rs, crates/core/src/commands/backup.rs, crates/core/src/commands/check.rs, crates/core/src/commands/repair/index.rs, crates/core/src/commands/repair/snapshots.rs, crates/core/src/error.rs, crates/core/src/repofile/snapshotfile.rs, crates/core/src/repository/warm_up.rs, crates/core/tests/errors.rs, crates/core/tests/snapshots/errors__log_output_minimal_passes.snap, crates/core/tests/snapshots/errors__log_output_passes.snap
- adds `display_log()` to `RusticError` for a minimal display to be used in logging
- uses above method in error!/warn!/info! macros over the codebase
- added snapshot test to make sure the output is as expected
=> refactor(error): enhance error logging and output formatting

crates/backend/src/local.rs, crates/backend/src/opendal.rs, crates/backend/src/rclone.rs, crates/backend/src/rest.rs, crates/core/src/backend.rs, crates/core/src/backend/cache.rs, crates/core/src/backend/decrypt.rs, crates/core/src/backend/dry_run.rs, crates/core/src/backend/hotcold.rs, crates/core/src/backend/warm_up.rs, crates/core/src/repository.rs, crates/testing/src/backend.rs
Add `getters` to warn about `async_incompatible` backends.
Using the type system or fixing all async compatibility issue is big and structural work.
To avoid runtime crash for our users I suggest using this getter as a temporary fix. 
tracking issue: rustic-rs/rustic#1181 (see for more details)
=> feat(async): add `async_compatible` methods to identify backend compatibility

.github/workflows/ci-heavy.yml, .github/workflows/cross-ci.yml, Cargo.lock
Signed-off-by: simonsan <14062932+simonsan@users.noreply.github.com>
=> ci: mirror targets for rustic in cross-ci and try to fix build

crates/core/src/commands/forget.rs
I am not very experienced with contributing to projects like rustic, so please correct me if I make any mistakes or could improve something about this PR!
In this case, I am particularly unsure about the commit message and how to add tests, so any tips there would be appreciated :smile:
As creating a rustic snapshot can be really fast if not much has changed (less than 10s), I have started to backup-up my files every ten minutes, but noticed that rustic doesn't yet have any keep-options for sub-hourly snapshots, so I decided to add them!
=> feat: Add a "minutely" timeline

crates/core/src/chunker.rs
=> fix(chunker): Don't underflow with wrong size_hint

crates/core/src/repository.rs, crates/core/src/vfs.rs, crates/core/tests/integration.rs
There was a bug when using partition_point which in that case does not gave guarentees about its behavior. Hence the whole logic was refactored and unit/integration tests were added.
closes https://github.com/rustic-rs/rustic/issues/1380
=> fix!: Don't panic when reading empty files

crates/core/src/repository.rs, crates/core/src/repository/warm_up.rs
This allows to programmatically (with script) wait for elements to be ready, instead of hardcoding a duration.
<details><summary>Scripts examples</summary>
Warm-up:
```bash
KEY="data/${1:0:2}/$1";
if [ "$(aws s3api head-object --bucket cold --key "$KEY" --query StorageClass)" == '"GLACIER"' ]
then
aws s3api restore-object --restore-request Days=7 --bucket cold --key "$KEY"
fi
```  
Warm-up wait:
```bash
KEY="data/${1:0:2}/$1";
until [ "$(aws s3api head-object --bucket cold --key "$KEY" --query StorageClass)" != '"GLACIER"' ]
do
sleep 60s
done
```
</details>
This is a simple version that will wait for each object sequentially (but that shouldn't be a problem as all warm up request are done in a first pass, and thus runs in parallel). 
I'm up for discussion if another model looks good, like …
=> feat(warmup)!: Add warmup wait command

.github/workflows/audit.yml, .github/workflows/careful.yml, .github/workflows/ci-heavy.yml, .github/workflows/coverage.yaml, Cargo.toml, README.md, crates/backend/Cargo.toml, crates/backend/README.md, crates/config/Cargo.toml, crates/config/README.md, crates/core/Cargo.toml, crates/core/README.md, crates/core/src/lib.rs, crates/core/src/repofile/keyfile.rs, crates/core/src/repofile/snapshotfile.rs, crates/core/tests/integration.rs, crates/core/tests/integration/backup.rs, crates/core/tests/integration/find.rs, crates/core/tests/integration/ls.rs, crates/core/tests/integration/prune.rs, crates/core/tests/integration/vfs.rs, crates/testing/Cargo.toml
=> chore: update to 2024 edition and fix clippy lints

crates/core/src/repofile/keyfile.rs, crates/core/src/repository.rs, crates/core/tests/integration/key.rs
Add methods to `Repository` to find ids by `str` and to stream files given in a list.
=> feat(repository): Add find_ids and stream_files_list

crates/core/src/repository.rs, crates/core/tests/integration/key.rs
`delete_key` used a `str` and searched for a matching `KeyId`. Now this methods allows to specify a `KeyId` directly. 
In #411 there is `find_ids` which can be used to search for matching Ids.
=> fix(repository): use KeyId in delete_key()
